name: 'GitHub Actions BingWallpaper'

on:
  push:
    branches: 
      - main
  schedule:
      - cron: '0 14 * * *'
jobs:
  BingWallpaperBot:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: 'Set up Python'
        uses: actions/setup-python@v1
        with:
          python-version: 3.8
      - name: 'Install requirements'
        run: pip install -r ./code/requirements.txt
      - name: 'Working'
        run: bash ./main.sh
      - name: Commit files
        run: |
         git config --local user.email "collapse_edge@outlook.com"
         git config --local user.name "CollapseEdge"
         git add .
         git commit -m "update today's wallpaper"
      - name: Push changes
        uses:  ad-m/github-push-action@main
        with:
          github_token: ${{ secrets.MY_GIT_TOKEN }}
          branch: main

