name: 'GitHub Actions BingWallpaper'

on:
  push:
    branches: 
      - main
  schedule:
      - cron: '0 14 * * *'
jobs:
  BingWallpaperBot:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: 'Set up Python'
        uses: actions/setup-python@v1
        with:
          python-version: 3.8
      - name: 'Install requirements'
        run: pip install -r ./code/requirements.txt
      - name: 'Working'
        run: bash ./code/main.sh
      - name: Commit files
        run: |
         git config --local user.email "123354572+CollapseEdge@users.noreply.github.com"
         git config --local user.name "CollapseEdge"
         git add .
         git commit -m "update today's wallpaper"
         git pull
      - name: Push changes
        uses:  ad-m/github-push-action@master
        with:
         github_token: ${{ secrets.MY_GIT_TOKEN }}
         branch: main
         force: true
